---
galaxy_info:
  author: isa
  description: Wspolna rola rejestracji PMM w trybie agent i agentless
  license: Proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - all

dependencies: []
